#!/usr/bin/env python3
"""Resolve and download one fixed Windows Update payload.

Fixed inputs (argv): Windows Update update ID, payload file ID (GUID),
payload file name, payload size in bytes, payload SHA-1 digest.

The Microsoft Windows Update service (anonymous SOAP, no account) returns a
short-lived signed CDN URL for the requested update; the bytes are then
downloaded from the Microsoft CDN.  The Guix daemon enforces the package's
fixed-output hash; this script only checks the WU-side identity (digest,
file GUID, size) and fails closed on anything unexpected.

No fallbacks: a fixed source that cannot be fetched is a fetch failure.
"""

import base64
import html
import os
import random
import re
import ssl
import sys
import time
import urllib.request
import xml.etree.ElementTree as ET

UPDATE_ID, FILE_ID, FILE_NAME, EXPECTED_SIZE, EXPECTED_SHA1, OUTPUT = sys.argv[1:]
EXPECTED_SIZE = int(EXPECTED_SIZE)

bundle_path = os.environ.get("SSL_CERT_FILE")
print(f"uup-fetch: ssl cert file={bundle_path!r} "
      f"dir={os.environ.get('SSL_CERT_DIR')!r}", flush=True)
if bundle_path:
    print(f"uup-fetch: bundle exists={os.path.isfile(bundle_path)} "
          f"size={os.path.getsize(bundle_path) if os.path.isfile(bundle_path) else 0}",
          flush=True)
print(f"uup-fetch: verify paths={ssl.get_default_verify_paths()}", flush=True)

FE3 = "https://fe3.delivery.mp.microsoft.com/ClientWebService/client.asmx"
FE3_SECURED = "https://fe3cr.delivery.mp.microsoft.com/ClientWebService/client.asmx/secured"
USER_AGENT = "Windows-Update-Agent/10.0.10011.16384 Client-Protocol/2.50"

BUILD = "10.0.26100.9278"          # device attributes: pinned build
ARCH = "amd64"
SKU = 48


def fail(msg):
    raise SystemExit(f"uup-fetch: {msg}")


def rand_hex(n):
    return "".join(random.choice("0123456789abcdef") for _ in range(n))


def device_ticket():
    """Fabricated (non-attested) Windows Update device ticket, exactly as
    generated by the reference UUP client implementations."""
    header = "13003002c377040014d5bcac7a66de0d50beddf9bba16c87edb9e019898000"
    t = base64.b64encode(bytes.fromhex(header + rand_hex(1054) + "b401")).decode()
    return base64.b64encode("\0".join("t=" + t + "&p=").encode()).decode()


def w3c(ts):
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(ts))


def device_attributes():
    """Device attributes for a retail Windows 11 24H2 amd64 client."""
    now = int(time.time())
    attrs = [
        "App=WU_OS", f"AppVer={BUILD}", "AttrDataVer=352",
        "AllowInPlaceUpgrade=1", "AllowOptionalContent=1",
        "AllowUpgradesWithUnsupportedTPMOrCPU=1", "BlockFeatureUpdates=0",
        "BranchReadinessLevel=CB", "CIOptin=1", "CurrentBranch=ge_release",
        f"DataExpDateEpoch_GE25H2={now+82800}",
        f"DataExpDateEpoch_GE24H2={now+82800}",
        f"DataExpDateEpoch_GE24H2Setup={now+82800}",
        f"DataExpDateEpoch_CU23H2={now+82800}",
        f"DataExpDateEpoch_CU23H2Setup={now+82800}",
        f"DataExpDateEpoch_NI22H2={now+82800}",
        f"DataExpDateEpoch_NI22H2Setup={now+82800}",
        f"DataExpDateEpoch_CO21H2={now+82800}",
        f"DataExpDateEpoch_CO21H2Setup={now+82800}",
        f"DataExpDateEpoch_23H2={now+82800}", f"DataExpDateEpoch_22H2={now+82800}",
        f"DataExpDateEpoch_21H2={now+82800}", f"DataExpDateEpoch_21H1={now+82800}",
        f"DataExpDateEpoch_20H1={now+82800}", f"DataExpDateEpoch_19H1={now+82800}",
        "DataVer_RS5=2000000000", "DefaultUserRegion=191",
        "DeviceFamily=Windows.Desktop", "DeviceInfoGatherSuccessful=1",
        "EKB19H2InstallCount=1", "EKB19H2InstallTimeEpoch=1255000000",
        "FlightingBranchName=", "FlightRing=Retail", "Free=gt64",
        "GStatus_GE24H2=2", "GStatus_GE24H2Setup=2", "GStatus_CU23H2=2",
        "GStatus_CU23H2Setup=2", "GStatus_NI23H2=2", "GStatus_NI22H2=2",
        "GStatus_NI22H2Setup=2", "GStatus_CO21H2=2", "GStatus_CO21H2Setup=2",
        "GStatus_22H2=2", "GStatus_21H2=2", "GStatus_21H1=2", "GStatus_20H1=2",
        "GStatus_20H1Setup=2", "GStatus_19H1=2", "GStatus_19H1Setup=2",
        "GStatus_RS5=2", f"GenTelRunTimestamp_19H1={now-3600}",
        "InstallDate=1438196400", "InstallLanguage=en-US",
        "InstallationType=Client", "IsDeviceRetailDemo=0",
        "IsFlightingEnabled=0", "IsRetailOS=1", "LaunchUserOOBE=1",
        "LCUVer=0.0.0.0", "MediaBranch=", f"MediaVersion={BUILD}",
        "CloudPBR=1", "DUScan=1", "OEMModel=21F6CTO1WW",
        "OEMModelBaseBoard=21F6CTO1WW", "OEMName_Uncleaned=LENOVO",
        "OemPartnerRing=UPSFlighting", f"OSArchitecture={ARCH}",
        f"OSSkuId={SKU}", "OSUILocale=en-US", f"OSVersion={BUILD}",
        "ProcessorIdentifier=Intel64 Family 6 Model 186 Stepping 3",
        "ProcessorManufacturer=GenuineIntel",
        "ProcessorModel=13th Gen Intel(R) Core(TM) i7-1355U",
        "ProductType=WinNT", "ReleaseType=Production",
        "SdbVer_20H1=2000000000", "SdbVer_19H1=2000000000",
        "SecureBootCapable=1", "TelemetryLevel=3",
        f"TimestampEpochString_GE24H2={now-3600}",
        f"TimestampEpochString_GE24H2Setup={now-3600}",
        f"TimestampEpochString_CU23H2={now-3600}",
        f"TimestampEpochString_CU23H2Setup={now-3600}",
        f"TimestampEpochString_NI23H2={now-3600}",
        f"TimestampEpochString_NI22H2={now-3600}",
        f"TimestampEpochString_NI22H2Setup={now-3600}",
        f"TimestampEpochString_CO21H2={now-3600}",
        f"TimestampEpochString_CO21H2Setup={now-3600}",
        f"TimestampEpochString_22H2={now-3600}", f"TimestampEpochString_21H2={now-3600}",
        f"TimestampEpochString_21H1={now-3600}", f"TimestampEpochString_20H1={now-3600}",
        f"TimestampEpochString_19H1={now-3600}", "TPMVersion=2",
        "UpdateManagementGroup=2", "UpdateOfferedDays=0",
        "UpgEx_GE24H2Setup=Green", "UpgEx_GE24H2=Green", "UpgEx_CU23H2=Green",
        "UpgEx_NI23H2=Green", "UpgEx_NI22H2=Green", "UpgEx_CO21H2=Green",
        "UpgEx_23H2=Green", "UpgEx_22H2=Green", "UpgEx_21H2=Green",
        "UpgEx_21H1=Green", "UpgEx_20H1=Green", "UpgEx_19H1=Green",
        "UpgEx_RS5=Green", "UpgradeAccepted=1", "UpgradeEligible=1",
        "UserInPlaceUpgrade=1", "VBSState=2", "Version_RS5=2000000000",
        "Win10CommercialAzureESUEligible=1",
        "Win10CommercialKeybasedESUEligible=1",
        "Win10CommercialW365ESUEligible=1", "Win10ConsumerESUStatus=3",
        "Win10ConsumerESUAY=9", f"WuClientVer={BUILD}",
    ]
    return html.escape("E:" + "&".join(attrs))


def uuid4():
    return "%08x-%04x-%04x-%04x-%04x%08x" % (
        random.getrandbits(32), random.getrandbits(16),
        random.getrandbits(16) | 0x4000, random.getrandbits(16) | 0x8000,
        random.getrandbits(32), random.getrandbits(32))


def envelope(action, to, body):
    now = int(time.time())
    return f"""<s:Envelope xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:s="http://www.w3.org/2003/05/soap-envelope">
<s:Header>
<a:Action s:mustUnderstand="1">{action}</a:Action>
<a:MessageID>urn:uuid:{uuid4()}</a:MessageID>
<a:To s:mustUnderstand="1">{to}</a:To>
<o:Security s:mustUnderstand="1" xmlns:o="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
<Timestamp xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
<Created>{w3c(now)}</Created>
<Expires>{w3c(now+120)}</Expires>
</Timestamp>
<wuws:WindowsUpdateTicketsToken wsu:id="ClientMSA" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wuws="http://schemas.microsoft.com/msus/2014/10/WindowsUpdateAuthorization">
<TicketType Name="MSA" Version="1.0" Policy="MBI_SSL">
<Device>{device_ticket()}</Device>
</TicketType>
</wuws:WindowsUpdateTicketsToken>
</o:Security>
</s:Header>
<s:Body>{body}</s:Body>
</s:Envelope>"""


def post(url, xml):
    """HTTPS POST with normal TLS verification: the builder sets
    SSL_CERT_FILE/SSL_CERT_DIR (standard CA bundle + pinned Microsoft CAs)."""
    req = urllib.request.Request(
        url, data=xml.encode(),
        headers={"User-Agent": USER_AGENT,
                 "Content-Type": "application/soap+xml; charset=utf-8"})
    with urllib.request.urlopen(req, timeout=120) as resp:
        return resp.read().decode("utf-8", "replace")


def get_cookie():
    now = w3c(int(time.time()))
    body = f"""<GetCookie xmlns="http://www.microsoft.com/SoftwareDistribution/Server/ClientWebService">
<oldCookie><Expiration>{now}</Expiration></oldCookie>
<lastChange>{now}</lastChange>
<currentTime>{now}</currentTime>
<protocolVersion>2.0</protocolVersion>
</GetCookie>"""
    out = post(FE3, envelope(
        "http://www.microsoft.com/SoftwareDistribution/Server/ClientWebService/GetCookie",
        FE3, body))
    root = ET.fromstring(out)
    for el in root.iter():
        if el.tag.rsplit("}", 1)[-1] == "EncryptedData" and el.text:
            return el.text.strip()
    fail("GetCookie: no EncryptedData in response")


def get_file_locations(cookie):
    now = w3c(int(time.time()))
    body = f"""<GetExtendedUpdateInfo2 xmlns="http://www.microsoft.com/SoftwareDistribution/Server/ClientWebService">
<updateIDs>
<UpdateIdentity><UpdateID>{UPDATE_ID}</UpdateID><RevisionNumber>1</RevisionNumber></UpdateIdentity>
</updateIDs>
<infoTypes>
<XmlUpdateFragmentType>FileUrl</XmlUpdateFragmentType>
<XmlUpdateFragmentType>FileDecryption</XmlUpdateFragmentType>
<XmlUpdateFragmentType>EsrpDecryptionInformation</XmlUpdateFragmentType>
<XmlUpdateFragmentType>PiecesHashUrl</XmlUpdateFragmentType>
<XmlUpdateFragmentType>BlockMapUrl</XmlUpdateFragmentType>
</infoTypes>
<deviceAttributes>{device_attributes()}</deviceAttributes>
<cookie><Expiration>{w3c(int(time.time())+3600)}</Expiration><EncryptedData>{cookie}</EncryptedData></cookie>
</GetExtendedUpdateInfo2>"""
    out = post(FE3_SECURED, envelope(
        "http://www.microsoft.com/SoftwareDistribution/Server/ClientWebService/GetExtendedUpdateInfo2",
        FE3_SECURED, body))
    root = ET.fromstring(out)
    locations = []
    for el in root.iter():
        if el.tag.rsplit("}", 1)[-1] != "FileLocation":
            continue
        digest = url = None
        for child in el:
            name = child.tag.rsplit("}", 1)[-1]
            if name == "FileDigest":
                digest = (child.text or "").strip()
            elif name == "Url":
                url = html.unescape((child.text or "").strip())
        if digest and url:
            locations.append((base64.b64decode(digest).hex(), url))
    if not locations:
        fail("GetExtendedUpdateInfo2: no FileLocations in response")
    return locations


def main():
    cookie = get_cookie()
    locations = get_file_locations(cookie)

    url = None
    for digest, candidate in locations:
        if digest == EXPECTED_SHA1:
            url = candidate
            break
    if url is None:
        fail(f"file digest {EXPECTED_SHA1} not among "
             f"{len(locations)} FileLocations")

    # The signed URL embeds the content-addressed file GUID.
    if re.search(r"/files/" + re.escape(FILE_ID) + r"(?:\?|$)", url) is None:
        fail(f"URL file ID mismatch: {FILE_ID} not in {url[:120]}")

    print(f"uup-fetch: resolved {FILE_NAME} ({EXPECTED_SIZE} B, "
          f"sha1 {EXPECTED_SHA1}) -> {url[:90]}...", flush=True)

    with urllib.request.urlopen(url, timeout=600) as resp:
        data = resp.read()
    if len(data) != EXPECTED_SIZE:
        fail(f"size mismatch: expected {EXPECTED_SIZE}, got {len(data)}")
    with open(OUTPUT, "wb") as f:
        f.write(data)
    print(f"uup-fetch: downloaded {len(data)} bytes to {OUTPUT}", flush=True)


if __name__ == "__main__":
    main()
